version: 2
jobs:
  build:
    docker:
      - image: benweese/test_automation
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pipenv install --dev
      - run:
          name: Run Test
          command: |
            pipenv run pytest
