version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-browsers

      - run:
          command: |
            pip3 install pipenv
            pipenv install
            pipenv run python3 tests/test_formsPage.py
