name: Python package

on: [push]

jobs:

  build_container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile
      
  build:
    runs-on: ubuntu-latest
    needs: build_container
    container:
      image: benweese/test_automation
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependancies
      run: pipenv install --dev
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: pipenv run pytest --junitxml=~/test-results/junit/results.xml
